### ISSUE TITLE
Improve API Specification 

### ISSUE THREAD

**Issue by mojo2012** [DivanteLtd/vue-storefront-integration-boilerplate#9]
Hi guys,

I'm currently trying to implement the API without any magento using my own little framework https://spot-next.io.
Some stuff like cart manipulation are pretty straight  forward. But some calls are more or less useless, like `GET /vsbridge/products/index`. It seems there are some customized values there, that work for a customized magento apparel store, but are useless for another store, like `accessories_type`. Some other properties like `attribute_set_id` are just useless either. What is their meaning?

I have not worked with magento, so maybe for a magento dev this is all easy. But shouldn't it be easy for any developer?

The best approach would be to have some diagrams, showing the data model. This would make it easy to understand what is what. As an alternative, at least provide property-level description.

**Comment by janmyszkier** [comment]
It makes sense, the API docs should only include the fields that are indeed crucial for the integration to work and not include random magento response. I'll see If I can remove some of it to make the sample response cleaner a bit.

**Comment by pkarw** [comment]
@janmyszkier check out this one: https://github.com/DivanteLtd/vue-storefront-simple-api/tree/develop/data/json - this is the very minimal set of fields required for VS to work for some catalog entities

**Comment by janmyszkier** [comment]
@pkarw the problem is, the data there doesn't seem to be up-to-date enough either, see my comment on:
https://github.com/DivanteLtd/vue-storefront-integration-boilerplate/issues/11#issuecomment-467367882

I'll try to tackle both issues in integration boilerplate at once but I think the examples are too scattered right now and it's hard to keep them all up to date with each other. It would make sense to keep them up to date in `vue-storefront` repo docs, and THEN reference the response files (not as code, but as links) in boilerplate repo so we only have to update the response json once (usually when we also change the code that goes along with it).

**Comment by pkarw** [comment]
Ok, cool please feel free to propose the changes where you find it suitable. This is surely an area that could  be improved a lot
